# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rgb.xdc

# Block Designs: bd/Zybo_periph/Zybo_periph.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph || ORIG_REF_NAME==Zybo_periph} -quiet] -quiet

# IP: bd/Zybo_periph/ip/Zybo_periph_processing_system7_0_1/Zybo_periph_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph_processing_system7_0_1 || ORIG_REF_NAME==Zybo_periph_processing_system7_0_1} -quiet] -quiet

# IP: bd/Zybo_periph/ip/Zybo_periph_pwm_0_0/Zybo_periph_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph_pwm_0_0 || ORIG_REF_NAME==Zybo_periph_pwm_0_0} -quiet] -quiet

# IP: bd/Zybo_periph/ip/Zybo_periph_ps7_0_axi_periph_0/Zybo_periph_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zybo_periph_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zybo_periph/ip/Zybo_periph_rst_ps7_0_100M_0/Zybo_periph_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zybo_periph_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zybo_periph/ip/Zybo_periph_auto_pc_0/Zybo_periph_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_periph_auto_pc_0 || ORIG_REF_NAME==Zybo_periph_auto_pc_0} -quiet] -quiet

# XDC: bd/Zybo_periph/Zybo_periph_ooc.xdc
