# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/brown/Documents/sw/zybo/zybo_pwm_led_multicolor/zybo_pwm_led_multicolor.srcs/sources_1/bd/Zybo_periph/ip/Zybo_periph_processing_system7_0_1/Zybo_periph_processing_system7_0_1.xci
# IP: The module: 'Zybo_periph_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brown/Documents/sw/zybo/zybo_pwm_led_multicolor/zybo_pwm_led_multicolor.srcs/sources_1/bd/Zybo_periph/ip/Zybo_periph_processing_system7_0_1/Zybo_periph_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zybo_periph_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/brown/Documents/sw/zybo/zybo_pwm_led_multicolor/zybo_pwm_led_multicolor.srcs/sources_1/bd/Zybo_periph/ip/Zybo_periph_processing_system7_0_1/Zybo_periph_processing_system7_0_1.xci
# IP: The module: 'Zybo_periph_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brown/Documents/sw/zybo/zybo_pwm_led_multicolor/zybo_pwm_led_multicolor.srcs/sources_1/bd/Zybo_periph/ip/Zybo_periph_processing_system7_0_1/Zybo_periph_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zybo_periph_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
